-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS kayttaja CASCADE;
DROP TABLE IF EXISTS askare CASCADE;
DROP TABLE IF EXISTS luokka CASCADE;
DROP TABLE IF EXISTS kayttajaAskare CASCADE;
DROP TABLE IF EXISTS kayttajaLuokka CASCADE;
DROP TABLE IF EXISTS askareLuokka CASCADE;
