-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS kayttaja CASCADE;
DROP TABLE IF EXISTS askare CASCADE;
DROP TABLE IF EXISTS luokka CASCADE;
DROP TABLE IF EXISTS kayttajaaskare CASCADE;
DROP TABLE IF EXISTS kayttajaluokka CASCADE;
DROP TABLE IF EXISTS askareluokka CASCADE;
